# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# ignore all warnings from all pods
inhibit_all_warnings!

target 'TECPROTEC' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

pod 'ACFloatingTextfield-Objc', '~> 1.3'
pod 'TPKeyboardAvoiding', '~> 1.3'
pod 'MXSegmentedPager'
pod 'HCSStarRatingView', '~> 1.5'
pod 'YLProgressBar', '~> 3.10'
pod 'BEMCheckBox', '~> 1.4'
pod 'Reachability', '~> 3.2'
pod 'SLExpandableTableView', '~> 1.3'
pod 'STHTTPRequest', '~> 1.1'
pod 'SVProgressHUD', '~> 2.1'
pod 'LGAlertView', '~> 2.4'
pod 'SDWebImage', '~> 4.0'
pod 'DRPLoadingSpinner', '~> 1.2'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'GoogleAnalytics'
pod 'AFNetworking'
pod 'JTSImageViewController', '~> 1.5'
pod 'Fabric'
pod 'Crashlytics'
pod 'KBContactsSelection'
pod 'GPUImage', '~> 0.1'

    
target 'TECPROTECTests' do
inherit! :search_paths
# Pods for testing
end

target 'TECPROTECUITests' do
inherit! :search_paths
# Pods for testing
end

end
